#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import subprocess
import sys


def upgrade_pip():
    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--upgrade", "pip"], check=True
        )
        print("✅ pip upgraded successfully.")
    except subprocess.CalledProcessError as e:
        print(f"⚠️ Failed to upgrade pip: {e}")


def install_argon2():
    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "--quiet", "argon2-cffi"],
            check=True,
        )
        print("✅ argon2-cffi installed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"❌ Error occurred while installing argon2-cffi: {e}")


# Upgrade pip first, then install
upgrade_pip()
install_argon2()
