#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import subprocess

def install_argon2():
    command = ["pip", "install", "argon2-cffi"]
    try:
        subprocess.run(command, check=True)
        print("argon2-cffi installed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error occurred while installing argon2-cffi: {str(e)}")

install_argon2()