#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
from argon2 import PasswordHasher

# agent is a NethServer library which provides function to communicate with the agent
import agent

data = json.load(sys.stdin)
VAULTWARDEN_ADMIN_TOKEN = data.get("ADMIN_TOKEN", "")


# Create a PasswordHasher object with the desired parameters
ph = PasswordHasher(
    time_cost=3, memory_cost=65540, parallelism=4, hash_len=32, salt_len=16
)

# Generate a random salt
salt = os.urandom(32)

# Hash the password
hashed_admin_token = ph.hash(VAULTWARDEN_ADMIN_TOKEN)

# vaultwarden domain settings
host = data.get("host", "")
DOMAIN = "https://" + host
# Testing SMTP Settings on Enviroment
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)
# Define missing variables
SENDS_ALLOWED = data.get("SENDS_ALLOWED", "")
EMERGENCY_ACCESS_ALLOWED = data.get("EMERGENCY_ACCESS_ALLOWED", "")
WEB_VAULT_ENABLED = data.get("WEB_VAULT_ENABLED", "")
SIGNUPS_ALLOWED = data.get("SIGNUPS_ALLOWED", False)
SIGNUPS_VERIFY = data.get("SIGNUPS_VERIFY", "")
SIGNUPS_VERIFY_RESEND_TIME = data.get("SIGNUPS_VERIFY_RESEND_TIME", "")
SIGNUPS_VERIFY_RESEND_LIMIT = data.get("SIGNUPS_VERIFY_RESEND_LIMIT", "")
SIGNUPS_DOMAINS_WHITELIST = data.get("SIGNUPS_DOMAINS_WHITELIST", "")
INVITATIONS_ALLOWED = data.get("INVITATIONS_ALLOWED", False)
PUSH_ENABLED = data.get("PUSH_ENABLED", "")
PUSH_RELAY_URI = data.get("PUSH_RELAY_URI", "")
PUSH_IDENTITY_URI = data.get("PUSH_IDENTITY_URI", "")
PUSH_INSTALLATION_ID = data.get("PUSH_INSTALLATION_ID", "")
PUSH_INSTALLATION_KEY = data.get("PUSH_INSTALLATION_KEY", "")
SHOW_PASSWORD_HINT = data.get("SHOW_PASSWORD_HINT", "")
app = {
    "DOMAIN": DOMAIN,
    "SENDS_ALLOWED": SENDS_ALLOWED,
    "EMERGENCY_ACCESS_ALLOWED": EMERGENCY_ACCESS_ALLOWED,
    "WEB_VAULT_ENABLED": WEB_VAULT_ENABLED,
    "SIGNUPS_ALLOWED": SIGNUPS_ALLOWED,
    "SIGNUPS_VERIFY": SIGNUPS_VERIFY,
    "SIGNUPS_VERIFY_RESEND_TIME": SIGNUPS_VERIFY_RESEND_TIME,
    "SIGNUPS_VERIFY_RESEND_LIMIT": SIGNUPS_VERIFY_RESEND_LIMIT,
    "SIGNUPS_DOMAINS_WHITELIST": SIGNUPS_DOMAINS_WHITELIST,
    "INVITATIONS_ALLOWED": INVITATIONS_ALLOWED,
    "LOGIN_RATELIMIT_MAX_BURST": "10",
    "LOGIN_RATELIMIT_SECONDS": "60",
    "ADMIN_RATELIMIT_MAX_BURST": "10",
    "ADMIN_RATELIMIT_SECONDS": "60",
    "SHOW_PASSWORD_HINT": SHOW_PASSWORD_HINT,
    "PUSH_ENABLED": PUSH_ENABLED,
    "PUSH_INSTALLATION_ID": PUSH_INSTALLATION_ID,
    "PUSH_INSTALLATION_KEY": PUSH_INSTALLATION_KEY,
    "PUSH_RELAY_URI": PUSH_RELAY_URI,
    "PUSH_IDENTITY_URI": PUSH_IDENTITY_URI,
    "SMTP_HOST": smtp_settings["host"],
    "SMTP_PORT": smtp_settings["port"],
    "SMTP_USERNAME": smtp_settings["username"],
    "SMTP_PASSWORD": smtp_settings["password"],
    "SMTP_ENCRYPTION": smtp_settings["encrypt_smtp"],
    "SMTP_FROM": smtp_settings["username"],
    "ADMIN_TOKEN": hashed_admin_token,
    "ADMIN_TOKEN_UNHASHED": VAULTWARDEN_ADMIN_TOKEN,
}

# Write everything into the env file at once
agent.write_envfile("vaultwarden.env", app)


# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
